### ISSUE TITLE
Fail to load module script

### ISSUE THREAD

**Issue by lajh87** [posit-dev/shiny-vscode#21]
I receive the following error in Chrome and VS Code Simple browser when trying to use `input.textarea` with `autoresize=True`.

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by gadenbuie** [comment]
It's been a while since this question was asked, and I hope you've found an answer! If not, please feel free to open a new issue with a complete, runnable Shiny app that we can use to investigate. Thanks!
