### ISSUE TITLE
QA Testing of rc-v0.2.0

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/shiny-vscode#51]
Two major features were added for rc-v0.2.0:

1. #30 
2. #44 

Follow-up issues found in this process:

1. https://github.com/posit-dev/shiny-vscode/pull/52

## Shiny for R apps

This feature brings support for running Shiny for R apps. The extension activates for R files named `app.R`, `ui.R`, `server.R`, `global.R`, `app-*.R` or `*-app.R`. Clicking the play button for such an app should run the app and preview it in the location determined by `shiny.previewType` (internal, external or none).

We need to check that this part of the extension works in the following environments:

1. macOS
2. Windows
	* For Windows, see the testing notes in #26, using a Shiny for R app in place of a Shiny for Python app.
	* Test in PowerShell, `cmd.exe` and Bash terminal environents.
4. Linux
5. GitHub Codespaces
6. Posit Workbench

## Shinylive

* Test that we can share single-file and multiple-file apps to Shinylive. (See #44 for details).
* Test that we can save single and multiple-file apps from Shinylive.
	* Single-file apps prompt users to pick a path to a file, e.g. `examples/app.py`. VS Code will prompt the user if they want to overwrite an existing file.
	* Multi-file apps prompt users to pick a non-existent directory.
* Apps should roundtrip: create a shinylive link, choose to copy it, then save the app from the shinylive link.
* Test hosts: both shinylive.io (released shiny) and posit-dev.github.io/shinylive (dev shiny)
* Test output locations: open in browser and copy
* Test modes: app or editor
* The above settings can be fixed by choosing default values in the settings UI.

For the purposes of testing the extension, a Shinylive link is successfully created when opening the app in editor mode contains the same code as seen locally. There are many reasons why an app my fail to actually run in Shinylive; if the code and files you intended to send are indeed included in the editor, then the link was successfully created. Similarly, saving a Shinylive app locally should create files containing the expected code.

**Comment by karangattu** [comment]
Testing is complete and was performed across MacOS, Windows 11, Ubuntu 22.04, Workbench and GitHub Codespaces.
Tested whether `app.R`, `app-*.R` can be previewed either internally or externally or None (no preview)
In addition, preview of already supported `app.py` was also verified.
The settings in the extension was overriden to change the preview location, the value for App or Editor mode and Open or copy the link across the above mentioned locations/devices.
Finally, creating shinylive links for single or multiple files from VS code and vice-versa was also tested.
