### ISSUE TITLE
Extension ID renaming plan

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/shiny-vscode#53]
In mid-May (when Joe gets back from vacation):

- [x] Publish new extension under `Posit.shiny`
	- [x] Check version number in package.json
	- [x] Update CHANGELOG.md
	- [x] Ensure CHANGELOG.md version number is correct
	- [x] Smoke test
	- [x] Create release on GitHub with a vX.Y.Z tag, pasting in the changelog entries
	- [x] Add `.vsix` to release artifacts
	- [x] Blog/slack if appropriate
	- [x] Close version milestone, reallocate issues if needed
	- [x] After publish, increment version number
- [x] Simultaneously, publish new version of `Posit.shiny-python` that removes all contribution points and depends on `Posit.shiny`, and rename to "[Deprecated] ..."
	- [x] Check version number in package.json
	- [x] Update CHANGELOG.md
	- [x] Ensure CHANGELOG.md version number is correct
	- [x] Smoke test
	- [x] Create release on GitHub with a vX.Y.Z tag, pasting in the changelog entries
	- [x] Add `.vsix` to release artifacts
- [x] Unpublish the [very old, long-deprecated `rstudio.pyshiny`](https://marketplace.visualstudio.com/items?itemName=rstudio.pyshiny) so we don't have two deprecated extensions showing up in search
- [x] Review usage of `Posit.shiny-python` and PR the name change (e.g. `Posit.shiny-python` is a recommended extension in py-shiny)

**Comment by gadenbuie** [comment]
A good outline of the process: https://github.com/microsoft/vscode/issues/59918#issuecomment-483412662

**Comment by gadenbuie** [comment]
Apparently we can also add a note in this thread for an official deprecation notice in the extension marketplace https://github.com/microsoft/vscode-discussions/discussions/1
