### ISSUE TITLE
Define path to R executable

### ISSUE THREAD

**Issue by markstevicgeo** [posit-dev/shiny-vscode#61]
Hello, for me it would useful if I could somehow define the path to the R executable on my machine instead of using the RPATH environment variable.

Would it be possible to do something similar to the Python version where it looks for the path definied in the Python Extension? Instead looking for the path definined in the R Extension using the following record in setting.json.
`"r.rpath.windows":`

**Comment by gadenbuie** [comment]
> for me it would useful if I could somehow define the path to the R executable on my machine instead of using the RPATH environment variable. ... [e.g.] `r.rpath.windows`

Yes I think we could do this! For my own notes, the `r.rpath.{windows,mac,linux}` settings come from the [R Debugger extension](https://marketplace.visualstudio.com/items?itemName=RDebugger.r-debugger).
