### ISSUE TITLE
 shiny extension not working

### ISSUE THREAD

**Issue by vikasrawal** [posit-dev/shiny-vscode#67]
I have the shiny extension installed. But when I open an app.R, it does not load shiny extension. The "Run Source Code" button still sends the R code to radian console as any other R programme, and nothing happens. The app is not started. What do I need to do to get the shiny extension to come into play.

**Comment by gadenbuie** [comment]
Do you have a "Run Shiny App" option when you click the dropdown of the play button? If so, what does that do when you click it?

![image](https://github.com/user-attachments/assets/145e9cdd-4894-44e5-8891-ed40f96f9375)

**Comment by vikasrawal** [comment]
No, I just have the "Run Source" button. There is no "Run Shiny App". I am
attaching a screenshot. When I click the button, the code is sent to R, but
the shiny app does not start.

**Comment by vikasrawal** [comment]
![2024-07-27-061717_1920x1050_scrot](https://github.com/user-attachments/assets/2546e6d7-d024-4782-8815-63e95c19cc06)

**Comment by gadenbuie** [comment]
> There is no "Run Shiny App".

If you don't have the "Run Shiny App" option, then the extension isn't detecting that the `app.R` is a shiny app script. Our heuristics are pretty basic, do you have the code `library(shiny)` in your script? If not, try adding that line somewhere.

**Comment by vikasrawal** [comment]
That was the problem. I had library(shiny) declared in another file which was sourced from app.R (it is a file that I share with a cluster of apps, so it is convenient not having to write all that in each app).

It would be a good idea, for abundant clarity, if it is mentioned in the documentation that the extension comes into effect if the file is named app.R and has library(shiny) in it.

Thanks a lot for your help.
