### ISSUE TITLE
Running and debugging Shiny apps doesn't work in VSCodium

### ISSUE THREAD

**Issue by Banbury** [posit-dev/shiny-vscode#78]
I have installed the Shiny extension and the Python extension in VSCodium. When I click 'Run Shiny App' or 'Debug Shiny App', I get the following error message:
```
The Python extension is required to run Shiny apps. Please install it and try again.
```
Clicking the button 'Show Python extension', opens the Python extension, which is installed and enabled.

OS: Windows 11
Python: 3.10.10 in a virtual environment
Shiny: 1.1.0

**Comment by gadenbuie** [comment]
Which version of VSCodium are you using? Which version of the `ms-python` extension do you have installed? I just tried the extension with VSCodium 1.93.1 and the ms-python v2024.14.1 and the extension worked as expected (although I am on Mac).

**Comment by Banbury** [comment]
I disabled all extensions except ms-python and Shiny. It still doesn't work
If I disable ms-python, reload VSCodium and then enable ms-python again it works.
Until I restart VSCodium again. Then it doesn't work.

**Comment by gadenbuie** [comment]
If you open your user or workspace JSON settings, do you have `extensions.experimental.affinity` set anywhere? I can reproduce your issue if I add the following to my workspace settings

```json
"extensions.experimental.affinity": {
    "ms-python.python": 1
}
```

I can then fix it by giving the `posit.shiny` extension the same affinity

```json
"extensions.experimental.affinity": {
    "ms-python.python": 1,
    "posit.shiny": 1,
},
```

**Comment by Banbury** [comment]
Thank you. That was indeed the problem.
I believe the Jupyter extension added those. I have removed the affinity altogether, and it works now.
I'll close the issue, but maybe you can add this to the documentation?
